import json

# Gesammelte Feldlisten aus SE16 (nur Feldnamen aus labels)
new_tables = {
    # Batch 1 (bereits gespeichert)
    '/US4G/EQS_SUBSCR': ['GUID', 'PDOC_REF', 'DOC_NO', 'TIMESTAMP', 'SUBSCRIPTION_TYPE', 'MESSAGE_TYPE', 'RESPONSE_STATUS', 'SENDER', 'RECEIVER', 'DATEFROM', 'DATETO', 'INT_UI', 'EQSPODVIEW', 'EXT_TSVERSNO', 'PROFILE_GROUP', 'SETTLUNIT', 'SETTLUNIT_EXT', 'CONTROL_AREA', 'SETTLTERRITORY', 'PDOC_REF_END', 'CR_DATE', 'CR_TIME', 'CR_NAME', 'CH_DATE', 'CH_TIME', 'CH_NAME'],
    '/US4G/ESA_QUOC': ['DB_KEY', 'PARENT_KEY', 'MEASUREMENT_PRODUCT', 'OBIS_CODE'],
    '/US4G/ESA_QUOH': ['DB_KEY', 'QUOTATION_REF_NO', 'EARLIEST_START_DATE_TIME', 'PREPARATION_PERIOD', 'PREPARATION_PERIOD_UNIT', 'BINDING_VALIDITY_PERIOD', 'BINDING_VALIDITY_PERIOD_UNIT', 'REQ_REF_NO', 'ASSOC_SERV_PROV', 'OWN_SERV_PROV', 'CURRENCY', 'INT_UI', 'QUOTATION_MSG_STATUS', 'MSG_DATE_TIME'],
    '/US4G/ESA_QUOI': ['DB_KEY', 'PARENT_KEY', 'MEASUREMENT_PRODUCT_TYPE', 'MEASUREMENT_PRODUCT', 'ARTICLE_ID', 'PRICE'],
    '/US4G/ESA_REQH': ['DB_KEY', 'REQUEST_REF_NO', 'ASSOC_SERV_PROV', 'OWN_SERV_PROV', 'MSG_DATE_TIME', 'SERVICE_START_DATE_TIME', 'INT_UI', 'REJ_MSG_ID', 'REJ_CODE', 'REJ_CODELIST_ID', 'SOURCE_PDOC_NUM'],
    '/US4G/ESA_REQI': ['DB_KEY', 'PARENT_KEY', 'MEASUREMENT_PRODUCT_TYPE', 'MEASUREMENT_PRODUCT'],
    '/US4G/ESA_REQIT': ['DB_KEY', 'PARENT_KEY', 'REQ_TEXT_TYPE', 'TEXT_COUNT', 'FREE_TEXT'],
    '/US4G/ESA_REQSI': ['DB_KEY', 'PARENT_KEY', 'MESPRD_ITEM_CODE', 'UPPER_THRESHOLD', 'LOWER_THRESHOLD'],
    '/US4G/ESA_SUB': ['INT_UI', 'START_DATE', 'START_TIME', 'OWN_SERV_PROV', 'ASSOC_SERV_PROV', 'MES_PRODUCT', 'END_DATE', 'END_TIME', 'OBIS_CODE', 'ORDERS_REF', 'SUB_TYPE', 'CR_DATE', 'CR_TIME', 'CR_NAME', 'CH_DATE', 'CH_TIME', 'CH_NAME'],
    '/US4G/ESA_SUBS': ['ORDERS_REF', 'ASSOC_SERV_PROV', 'OBIS_CODE', 'OWN_SERV_PROV', 'INT_UI', 'START_DATE', 'START_TIME', 'MES_PRODUCT', 'END_DATE', 'END_TIME', 'SUB_TYPE', 'QUOTATION_REF_NO', 'CR_DATE', 'CR_TIME', 'CR_NAME', 'CH_DATE', 'CH_TIME', 'CH_NAME'],
    '/US4G/FRANCHISE': ['SPARTYP', 'VERTART', 'METER_PROC', 'EUSAGE', 'TARIFART', 'RATE_CATEGORY', 'FR_FEE_GROUP', 'FR_FEE_ASSIGN', 'FRANCHISE_FEE', 'FRANCHISE_AMOUNT', 'ARTICLE_NO'],
    '/US4G/FR_GRP_OPR': ['OPERAND', 'EUSAGE', 'PRIORITY'],
    '/US4G/GPKE_FACCL': ['EVENT', 'VALID_FROM', 'SOURCE', 'INSTANCE_CLASS', 'ACTIVE'],
    '/US4G/GRID_ATTR': ['GRID_ID', 'BIS', 'AB', 'GAS_QUALITY'],
    '/US4G/GUBV_OPR': ['OPERAND', 'PRIORITY'],
    '/US4G/HEATCONS_T': ['UBD_HEAT_CONSUMPT', 'SPRAS', 'UBD_HEAT_CONSUMPT_TXT'],
    '/US4G/HEAT_CONS': ['UBD_HEAT_CONSUMPT'],
    '/US4G/HEAT_CONSU': ['UBD_HEAT_CONSUMPT'],
    '/US4G/INTG_DDL': ['PROC_ID', 'IS_DDL_NEED', 'PERIOD_TYPE'],
    '/US4G/INTG_REL': ['PROC_ID', 'INT_REL'],
    '/US4G/INVC_REF_H': ['DB_KEY', 'BILL_SOL', 'INVDOC_REF', 'BILLDOC_REF', 'CROSSREFNO', 'MSG_DATE', 'REVERSAL', 'OPBEL', 'OPUPK', 'PROC_BUS_STATUS', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON'],
    '/US4G/INVC_REF_I': ['DB_KEY', 'PARENT_KEY', 'BO_TYPE', 'BO_UUID', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON'],
    '/US4G/INVLIST_HD': ['INV_LIST_ID', 'MSG_TIMESTAMP', 'VALID_START_MONTH', 'SENDER', 'RECEIVER', 'PDOC_REF', 'GROUP_REFERENCE', 'IS_SIMULATION'],
    '/US4G/INV_DISC': ['INT_INV_DOC_NO', 'LINE_GUID', 'INT_INV_DISC_NO', 'DISC_TYPE', 'DISC_QUAL', 'RABART', 'RABPROZ', 'DISC_BASE_AMOUNT', 'DISC_AMOUNT'],
    '/US4G/INV_REJINF': ['INT_INV_DOC_NO', 'LINE_GUID', 'REJ_REAS_COUNT', 'RSTGR', 'REJ_TEXT_COUNT', 'REJ_REAS_UBD', 'FREE_TEXT_VALUE', 'INVOIC_POSITION_NO', 'RELATED_INVOICE_MSG_REF', 'PREVIOUS_INVOICE_MSG_REF'],
    '/US4G/INV_TYP': ['BILL_SOL', 'INVOIC_IMD_QUAL', 'INVOIC_BGM_QUAL', 'DIVISION_CATEGORY', 'INVOICE_TYPE', 'DOC_TYPE'],
    '/US4G/IRLY_DEV': ['DB_KEY', 'PARENT_KEY', 'EQUNR', 'OPERATION_TYPE', 'EQUNR_REPLACED', 'MELO_INSTL', 'DEVLOC', 'REASON', 'COMM_TECH_WAN', 'COMM_TECH_HAN', 'COMM_TECH_LMN', 'COMM_SCENARIO', 'PRESSURE', 'ABRFAKT', 'PROGT', 'MATERIAL', 'SERIAL_NO', 'MAT_TXT', 'DEV_TXT', 'SERIAL_NO_R', 'DEV_TXT_R', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE', 'IR_DEV_EXTENDED'],
    '/US4G/IRLY_HEAD': ['DB_KEY', 'INST_REPLY_ID', 'PROC_REF', 'DATE_ACTIVITY', 'TIME_ACTIVITY', 'PLANNED_DATE_ACT', 'PLANNED_TIME_ACT', 'STATUS', 'PROC_SCENARIO', 'PROC_SCENARIO_OLD', 'HAUS', 'CONN_OBJ_ADDRESS', 'ETIMEZONE', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON', 'PREMISE_DETAIL', 'BUSINESSPARTNER', 'BUSINESSPARTNERNAME', 'POD', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE', 'IR_HEAD_EXTENDED'],
    '/US4G/IRLY_MTR': ['DB_KEY', 'PARENT_KEY', 'ROOT_KEY', 'REG_CODE', 'QUANTITIY_EXT', 'MEASURE_UNIT_EXT', 'PERVERBRD', 'NOT_USED', 'LOAD_CAPA', 'ABLHINW', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE', 'IR_MTR_EXTENDED'],
    '/US4G/IR_DEVICE': ['DB_KEY', 'PARENT_KEY', 'EQUNR', 'OPERATION_TYPE', 'EQUNR_REPLACED', 'MELO_INSTL', 'DEVLOC', 'REASON', 'COMM_TECH_WAN', 'COMM_TECH_HAN', 'COMM_TECH_LMN', 'COMM_SCENARIO', 'PRESSURE', 'ABRFAKT', 'PROGT', 'MATERIAL', 'IR_DEV_EXTENDED'],
    '/US4G/IR_DEV_DD': ['DB_KEY', 'PARENT_KEY', 'EQUNR', 'OPERATION_TYPE', 'EQUNR_REPLACED', 'DEVLOC', 'REASON', 'COMM_TECH_WAN', 'COMM_TECH_HAN', 'COMM_TECH_LMN', 'COMM_SCENARIO', 'PRESSURE', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE'],
    '/US4G/IR_HEAD': ['DB_KEY', 'INST_REPLY_ID', 'PROC_REF', 'DATE_ACTIVITY', 'TIME_ACTIVITY', 'PLANNED_DATE_ACT', 'PLANNED_TIME_ACT', 'STATUS', 'PROC_SCENARIO', 'PROC_SCENARIO_OLD', 'HAUS', 'ETIMEZONE', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON', 'IR_HEAD_EXTENDED'],
    '/US4G/IR_H_DD': ['DB_KEY', 'INST_REPLY_ID', 'PROC_REF', 'DATE_ACTIVITY', 'TIME_ACTIVITY', 'STATUS', 'PROC_SCENARIO', 'PROC_SCENARIO_OLD', 'HAUS', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE'],
    '/US4G/IR_MTRREAD': ['DB_KEY', 'PARENT_KEY', 'ROOT_KEY', 'REG_CODE', 'QUANTITIY_EXT', 'MEASURE_UNIT_EXT', 'PERVERBRD', 'NOT_USED', 'LOAD_CAPA', 'ABLHINW', 'IR_MTR_EXTENDED'],
    '/US4G/IR_MTR_DD': ['DB_KEY', 'PARENT_KEY', 'ROOT_KEY', 'REG_CODE', 'QUANTITIY_EXT', 'MEASURE_UNIT_EXT', 'PERVERBRD', 'ACTIVEUUID', 'HASACTIVEENTITY', 'DRAFTENTITYCREATIONDATETIME', 'DRAFTENTITYLASTCHANGEDATETIME', 'DRAFTADMINISTRATIVEDATAUUID', 'DRAFTENTITYCONSISTENCYSTATUS', 'DRAFTENTITYOPERATIONCODE'],
    '/US4G/KME_ENABLE': ['KME_ENABLE'],
    '/US4G/LBS_CODE_T': ['LBS_CODE', 'SPRAS', 'LBS_CODE_DESC'],
    '/US4G/LBS_MODLE': ['LBS_CODE', 'MCM_MODEL_ID', 'MODLE_IS_DEFAULT'],
    '/US4G/LBS_OBJCOD': ['OBJECT_CODE', 'OBJECT_TYPE', 'OBJECT_LEVEL'],
    '/US4G/LBS_OBJREF': ['LBS_CODE', 'OBJECT_CODE', 'REF_OBJECT_CODE_MELO', 'REF_OBJECT_CODE_NELO', 'FROM_DATE'],
    '/US4G/MALO_NR': ['OBJECT', 'SPARTE', 'GRID_ID', 'NUMKR', 'INACTIVE'],

    # Batch 2 (neu extrahiert)
    '/US4G/MAP_RSN': ['RSTGR'],
    '/US4G/MBDACMAP': ['HVORG', 'TVORG', 'TVORG_AC'],
    '/US4G/MDC_ASSPRC': ['MDC_EVENT_TYPE', 'ASSOC_PROC_ID', 'ASSOC_STEP_ID', 'UPDATE_STEP_ID', 'START_STEP_ID', 'DEFAULT_PROCESS', 'PRIORITY'],
    '/US4G/MDC_CLSMAP': ['PROC_ID', 'PROC_STEP_ID', 'CLASS', 'METHOD'],
    '/US4G/MDC_EVTMAP': ['MDC_EVENT_TYPE', 'PROC_ID'],
    '/US4G/MDC_VARPRO': ['PROCESS_ID', 'MDC_VARIANT'],
    '/US4G/MDR_ACTEV': ['OBJCATEG', 'OBJTYPE', 'EVENT', 'RECTYPE', 'STARTDATE', 'OWNER', 'CATEGORY', 'PROC_ID', 'SEQ_NO'],
    '/US4G/MDR_ADDFUN': ['SOURCE', 'PROCESS_OBJ', 'FUNCTION_POSITION', 'FUNCTION_NO', 'FUNCTION_MODULE'],
    '/US4G/MDR_ADD_FT': ['SPRAS', 'SOURCE', 'PROCESS_OBJ', 'FUNCTION_POSITION', 'FUNCTION_NO', 'FUNCTION_TEXT'],
    '/US4G/MDR_CONF': ['VALIDFROM', 'DISCDOCSTATUS', 'PROCESSSTATUS', 'MESSAGESTATUS', 'OKCODE', 'SCREENNR', 'SOURCE', 'ACTIVE', 'MSGID', 'MSGTY', 'MSGNO', 'MSGV1', 'MSGV2', 'MSGV3', 'MSGV4', 'DISPMSG', 'AUTHOBJECT'],
    '/US4G/MDR_DAIC': ['IC_CONTACT_ID', 'IC_CODE', 'IC_CODE_VALUE', 'IC_CONTACT'],
    '/US4G/MDR_DAICT': ['SPRAS', 'CONTACT_ID', 'IDTXT'],
    '/US4G/MDR_DIV_AT': ['SPARTE', 'INTCODE'],
    '/US4G/MDR_ME_PNT': ['DISCNO', 'DISCACT', 'ADD_INFO_1', 'ADD_INFO_2', 'ADD_INFO_3', 'ADD_INFO_4', 'ADD_INFO_5', 'STREET', 'CITY', 'POSTAL_CODE', 'ERDAT', 'ERNAM', 'AEDAT', 'AENAM', 'BEGRU', 'LOEVM', 'LANGU'],
    '/US4G/MDR_PROCV': ['DISCPROCV', 'COTYP', 'FORMKEY', 'SUP_PLANNED_DT_TY', 'MACO', 'MANUAL', 'REQ_RVERS_DC', 'REQ_RVERS_RC', 'REQ_RECON', 'RELEASE_STRATEGY', 'RELEASE_DEADLINE', 'CONTACT_ID', 'DAYS_EARL_ACTDATE'],
    '/US4G/MDR_TEXT': ['GUID', 'DISCNO', 'DISCACT', 'TEXT_TYPE', 'SEQUENCE', 'SERVICEID', 'MSGDATE', 'SEND_STAT', 'ERDAT', 'ERNAM', 'AEDAT', 'AENAM', 'BEGRU', 'LOEVM', 'LANGU'],
    '/US4G/MD_CUSTOM': ['NAME', 'NUMB', 'VALUE_1', 'VALUE_2', 'VALUE_3', 'VALUE_4', 'VALUE_5', 'VALUE_6', 'VALUE_7', 'VALUE_8', 'VALUE_9'],
    '/US4G/MD_CUST_PA': ['FALL', 'SPARTE', 'KONSTRUKT', 'VARIANTE', 'LFDNR', 'OBJECT', 'ATTRID', 'VALUE', 'EVALTYPE', 'TEXT', 'BEMERKUNG'],
    '/US4G/MD_DATALOG': ['CONSTRUCTS', 'VARIANT', 'MALO_POD', 'CREATEDON', 'CLIENT330', 'CLIENT340', 'CLIENT345', 'CLIENT350', 'DIVISION', 'CLIENT_SUP', 'CLIENT_MOS', 'CLIENT_DSO', 'CLIENT_DMOS'],
    '/US4G/MD_PARAM': ['MARKET_ROLE', 'DIVISION', 'CONSTRUCT', 'VARIANT', 'SORT_INDEX', 'OBJECT', 'PARAM', 'VALUE', 'EVALTYPE', 'DESCRIPTION', 'REMARK'],

    # Batch 3 (MESPRD, MET, MGV, MI - gerade extrahiert)
    '/US4G/MESPRD': ['MES_PRODUCT'],
    '/US4G/MESPRD2RUC': ['MES_PRODUCT', 'USE_TOU', 'RUC_ID', 'METERING_INTERVAL'],
    '/US4G/MESPRD2_AT': ['MES_PRODUCT', 'VALID_FROM_DATE', 'VALID_TO_DATE', 'DIVISION', 'MESD_LEVEL', 'PRODUCT_VALUE', 'PRODUCT_TYPE', 'DEAD_LINE', 'TRIGGER_FLAG', 'PROD_GRAN', 'REC_INTERVAL', 'TRANS_INTERVAL', 'TRANS_ROUTE', 'DIREC_QUAD', 'TOU_RELATED', 'VAL_QUALITY', 'CONF_PRIORITY', 'SEC_MEASUREMENT', 'TRANS_TO_DSO', 'MESPRD_SUPPORTED', 'MOS_ESA_MUST', 'SUB_TYPE_ESA', 'MESPRD_SW', 'MESPRD_PC'],
    '/US4G/MESPRDGRAN': ['PRODUCT_VALUE_GRANULE', 'MEAS_PERIOD'],
    '/US4G/MESPRDT': ['MES_PRODUCT', 'SPRAS', 'MES_PRODUCT_DESC'],
    '/US4G/MESPRD_ASE': ['MES_PRODUCT', 'VALID_FROM_DATE', 'SETTING_NAME', 'SETTING_VALUE'],
    '/US4G/MESPRD_AT': ['MES_PRODUCT', 'VALID_FROM_DATE', 'VALID_TO_DATE', 'TOU_SEL_OPTION', 'POD_CATEGORY', 'DIVISION', 'PRODUCT_VALUE', 'PRODUCT_TYPE', 'PRODUCT_VALUE_GRANULE', 'SUPPL_DIR', 'COMMU_TYPE', 'TRANSFER_GRANULE', 'DEAD_LINE', 'PRODUCT_QUAL', 'SEC_MEASUREMENT', 'TRANS_TO_DSO', 'MESPRD_SUPPORTED'],
    '/US4G/MESPRD_I': ['MES_PRODUCT', 'OBIS_CODE'],
    '/US4G/MESPRD_IR': ['MES_PRODUCT', 'VALID_FROM_DATE', 'MESD_ITEM_CODE', 'MESD_ITEM_MEASURE', 'MESD_ITEM_UNIT'],
    '/US4G/MESPRD_IT': ['MES_PRODUCT', 'SPRAS', 'MES_PRODUCT_DESC'],
    '/US4G/MESPRD_OBI': ['MES_PRODUCT', 'VALID_FROM_DATE', 'MARKET_ROLE', 'REG_CHANNEL_CODE', 'REG_TARIF_CODE'],
    '/US4G/MESPRD_OBS': ['OBIS_CODE', 'VALID_FROM_DATE', 'MES_PRODUCT'],
    '/US4G/MESPRD_OCH': ['MES_PRODUCT', 'VALID_FROM_DATE', 'VALID_TO_DATE', 'DIVISION_CAT', 'MESD_LEVEL', 'MES_ENERGY_DIR', 'MES_PROD_CHAPTER', 'MES_VALUE_DET_TYPE', 'MES_MAX_REPEAT'],
    '/US4G/MESPRD_OCI': ['MES_PRODUCT', 'VALID_FROM_DATE', 'MESD_ITEM_CODE'],
    '/US4G/MESPRD_OLC': ['MES_PRODUCT', 'VALID_FROM_DATE', 'VALID_TO_DATE', 'DIVISION_CAT', 'MESD_LEVEL', 'IND_REL_TO_DSO', 'IND_REL_TO_SUP'],
    '/US4G/MES_PROD': ['MES_PRODUCT', 'MES_PRODUCT_DESC', 'VALID_FROM_DATE', 'VALID_TO_DATE', 'DIVISION', 'POD_CATEGORY', 'PRODUCT_VALUE', 'PRODUCT_TYPE', 'PRODUCT_VALUE_GRANULE', 'SUPPL_DIR', 'COMMU_TYPE', 'TRANSFER_GRANULE', 'DEAD_LINE', 'PRODUCT_QUAL', 'SEC_MEASUREMENT', 'TRANS_TO_DSO'],
    '/US4G/MET_ENDI': ['EXT_ENERGY_DIR'],
    '/US4G/MET_ENDI_T': ['EXT_ENERGY_DIR', 'SPRAS', 'EXT_ENERGY_DIR_TXT'],
    '/US4G/MET_MOTY': ['EXT_MOUNT_TYP'],
    '/US4G/MET_MOTY_T': ['EXT_MOUNT_TYP', 'SPRAS', 'EXT_MOUNT_TYP_TXT'],
    '/US4G/MET_RATE': ['EXT_RATE_IND'],
    '/US4G/MET_RATE_T': ['EXT_RATE_IND', 'SPRAS', 'EXT_RATE_IND_TXT'],
    '/US4G/MGV_DETRC': ['QUANTITY_TYPE', 'DSO_RESELLER', 'MGV_RESELLER', 'REVERSE_CHARGE_TYPE'],
    '/US4G/MGV_GAMA': ['GRID_ACCOUNT_NO', 'SC_SP', 'DIST_SP', 'START_DATE', 'MERGED_INTO_GRID_ACCT_NO', 'GAS_QUALITY'],
    '/US4G/MGV_INFO': ['DB_KEY', 'PARENT_KEY', 'GRID_ACCOUNT_NO', 'SETTLE_QUANTITY', 'SETTLE_MEASURE_UNIT', 'SETTLE_RESP_START_DATE', 'SETTLE_RESP_END_DATE', 'GU_QUANTITY', 'GU_MEASURE_UNIT', 'QUANTITY_TYPE', 'QUANTITY', 'MEASURE_UNIT', 'APPLICATION_YEAR', 'APPLICATION_MONTH', 'CITID', 'INVDOCNO', 'OBSOLETE', 'CREATED_BY', 'CREATED_ON', 'CHANGED_BY', 'CHANGED_ON', 'MGV_DATA_EXTENDED'],
    '/US4G/MI_COMM': ['DB_KEY', 'PARENT_KEY', 'ROOT_KEY', 'DESTINATION_ADDRESS', 'CERTIFICATE_USER', 'CERTIFICATE_ISSUER', 'ENDPOINT_TYPE', 'SERVICE_PROVIDER', 'DESTINATION_ADDRESS_IPV4', 'DESTINATION_ADDRESS_IPV6', 'MI_COMM_EXTENDED'],
    '/US4G/MI_CP': ['INSTALLATION', 'MI_ID', 'MI_TEXT', 'MP_ID', 'MDUSIFACE', 'MI_VIEW', 'DATE_FROM', 'IM_REASON', 'DATE_PLANNED', 'IS_ALL', 'REP_TYPE', 'REMOVE_TYPE', 'DATE_PLANNED_EST', 'TOU_CODE', 'DEF_TYPE', 'CATEGORY', 'PURPOSE'],
    '/US4G/MI_DEV': ['DB_KEY', 'PARENT_KEY', 'ROOT_KEY', 'EQUNR', 'SERNR', 'DEVICE_CAT', 'DATE_FROM', 'DATE_TO', 'IS_IM', 'IS_SMGW', 'MI_DEV_EXTENDED'],
}

# Lade existierende JSON
with open('us4g_metadata.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Fuege neue Tabellen hinzu (vereinfachte Form - nur Feldnamen)
for table_name, fields in new_tables.items():
    if table_name not in data['tabellen']:
        data['tabellen'][table_name] = {
            'beschreibung': 'SE16-Extrakt (nur Feldnamen)',
            'anzahl_felder': len(fields),
            'felder': [{'feldname': f} for f in fields]
        }

# Update Fortschritt
data['fortschritt']['extrahiert'] = len(data['tabellen'])

# Speichern
with open('us4g_metadata.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"Gespeichert: {len(data['tabellen'])} Tabellen")
