"""
Data models for SAP Web GUI MCP Server.

This module contains Pydantic models and configuration classes.
"""

from sapwebguimcp.models.alv_models import (
    AlvCellInfo,
    AlvColumn,
    AlvMetadata,
    TableCellClickResult,
)
from sapwebguimcp.models.base import TCODE_PATTERN, PopupButton, PopupInfo, PopupType, SessionId, TCode, ToolResult
from sapwebguimcp.models.browser import (
    BrowserManager,
    close_browser_manager,
    get_browser_manager,
)
from sapwebguimcp.models.browser_results import (
    BrowserKeyboardResult,
    ClickResult,
    EvaluateResult,
    FillResult,
    HtmlResult,
    NavigateResult,
    ScreenshotResult,
    SelectOptionResult,
    SnapshotResult,
    WaitResult,
)
from sapwebguimcp.models.config import (
    BrowserMode,
    BrowserType,
    SapWebGuiSettings,
    get_settings,
)
from sapwebguimcp.models.intent_models import (
    FeedbackEntry,
    FeedbackLogResult,
    IntentEntry,
    IntentLogResult,
)
from sapwebguimcp.models.sap_results import (
    ButtonInfo,
    CapabilitiesResult,
    ClosePopupResult,
    DiscoveredButtons,
    DiscoveredFields,
    DropdownFillResult,
    DropdownInfo,
    FieldFillError,
    FieldInfo,
    FieldLookupResult,
    FillFormResult,
    FormField,
    FormFieldsProcessResult,
    FormFieldsResult,
    KeepaliveResult,
    KeyboardResult,
    LoginResult,
    SapFieldType,
    ScreenInfo,
    ScreenText,
    SessionStatus,
    SetFieldResult,
    ShortcutInfo,
    ShortcutsResult,
    StatusBarInfo,
    TableData,
    TableRow,
    ToolInfo,
    TransactionResult,
)
from sapwebguimcp.models.se11_models import (
    SE11Entry,
    SE11Error,
    SE11Field,
    SE11FileSummary,
    SE11ObjectType,
    SE11Result,
)
from sapwebguimcp.models.se16_models import (
    SE16FileSummary,
    SE16Result,
    SE16Row,
)
from sapwebguimcp.models.se24_models import (
    SE24Attribute,
    SE24Entry,
    SE24Error,
    SE24FileSummary,
    SE24Method,
    SE24MethodException,
    SE24MethodParameter,
    SE24ObjectType,
    SE24ParameterCategory,
    SE24Result,
    SE24Visibility,
)
from sapwebguimcp.models.se37_models import (
    SE37Entry,
    SE37Error,
    SE37Exception,
    SE37FileSummary,
    SE37Parameter,
    SE37ParameterCategory,
    SE37Result,
    SE37TypingMethod,
)
from sapwebguimcp.models.se93_models import (
    SE93Entry,
    SE93Error,
    SE93FileSummary,
    SE93Result,
    SE93TransactionType,
)
from sapwebguimcp.models.workflow_models import (
    Workflow,
    WorkflowDeleteResult,
    WorkflowError,
    WorkflowListResult,
    WorkflowRunResult,
    WorkflowSaveInput,
    WorkflowSaveResult,
    WorkflowSubmitResult,
)

__all__ = [
    # Base
    "TCODE_PATTERN",
    "PopupButton",
    "PopupInfo",
    "PopupType",
    "SessionId",
    "TCode",
    "ToolResult",
    # ALV models
    "AlvCellInfo",
    "AlvColumn",
    "AlvMetadata",
    "TableCellClickResult",
    # Config models
    "BrowserMode",
    "BrowserType",
    "SapWebGuiSettings",
    "get_settings",
    # Browser manager
    "BrowserManager",
    "get_browser_manager",
    "close_browser_manager",
    # SAP results
    "ButtonInfo",
    "CapabilitiesResult",
    "DiscoveredButtons",
    "DiscoveredFields",
    "ClosePopupResult",
    "DropdownFillResult",
    "DropdownInfo",
    "FieldFillError",
    "FieldInfo",
    "FieldLookupResult",
    "FillFormResult",
    "FormField",
    "FormFieldsProcessResult",
    "FormFieldsResult",
    "KeepaliveResult",
    "KeyboardResult",
    "LoginResult",
    "SapFieldType",
    "ScreenInfo",
    "ScreenText",
    "SessionStatus",
    "SetFieldResult",
    "ShortcutInfo",
    "ShortcutsResult",
    "StatusBarInfo",
    "TableData",
    "TableRow",
    "ToolInfo",
    "TransactionResult",
    # Browser results
    "BrowserKeyboardResult",
    "ClickResult",
    "EvaluateResult",
    "FillResult",
    "HtmlResult",
    "NavigateResult",
    "ScreenshotResult",
    "SelectOptionResult",
    "SnapshotResult",
    "WaitResult",
    # Intent and feedback models
    "FeedbackEntry",
    "FeedbackLogResult",
    "IntentEntry",
    "IntentLogResult",
    # SE11 models
    "SE11Entry",
    "SE11Error",
    "SE11Field",
    "SE11FileSummary",
    "SE11ObjectType",
    "SE11Result",
    # SE16 models
    "SE16FileSummary",
    "SE16Result",
    "SE16Row",
    # SE37 models
    "SE37Entry",
    "SE37Error",
    "SE37Exception",
    "SE37FileSummary",
    "SE37Parameter",
    "SE37ParameterCategory",
    "SE37Result",
    "SE37TypingMethod",
    # SE24 models
    "SE24Attribute",
    "SE24Entry",
    "SE24Error",
    "SE24FileSummary",
    "SE24Method",
    "SE24MethodException",
    "SE24MethodParameter",
    "SE24ObjectType",
    "SE24ParameterCategory",
    "SE24Result",
    "SE24Visibility",
    # SE93 models
    "SE93Entry",
    "SE93Error",
    "SE93FileSummary",
    "SE93Result",
    "SE93TransactionType",
    # Workflow models
    "Workflow",
    "WorkflowDeleteResult",
    "WorkflowError",
    "WorkflowListResult",
    "WorkflowRunResult",
    "WorkflowSaveInput",
    "WorkflowSaveResult",
    "WorkflowSubmitResult",
]
