name: Formatting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  formatting:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"

      - name: Check formatting
        run: |
          uv run --locked --group linting ruff format --check .
          uv run --locked --group linting ruff check --select I .
