name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"

      - name: Run pylint
        run: uv run --locked --group linting pylint sapguimcp
