name: Spell Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spell_check:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: src

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"

      - name: Run codespell
        run: |
          uv run --locked --group spell_check codespell --ignore-words=domain-specific-terms.txt src
          uv run --locked --group spell_check codespell --ignore-words=domain-specific-terms.txt README.md
